# Navigation Links
#   To link a homepage widget, specify the URL as a hash `#` followed by the filename of the
#     desired widget in your `content/home/` folder.
#   The weight parameter defines the order that the links will appear in.

main:
  - name: Home
    url: '#about'
    weight: 12
  - name: Working Papers
    url: '#working-papers'
    weight: 24
  - name: Publications
    url: '#featured'
    weight: 36
  - name: Talks
    url: '#talks'
    weight: 48
  - name: Teaching
    url: '#teaching'
    weight: 60
  - name: CV
    url: uploads/CV_Alejandro_Rojas.pdf
    weight: 72
 # - name: Teaching Evaluations
 #   URL: uploads/teaching_evaluations.pdf
 #   weight: 84
  - name: Contact
    url: '#contact'
    weight: 84

# Link to a PDF of your resume/CV from the menu.
# To enable, copy your resume/CV to `static/uploads/resume.pdf` and uncomment the lines below.
#  - name: CV
#    url: uploads/resume.pdf
#    weight: 70
